FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lockb* ./
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY libs/shared-schema/package.json ./libs/shared-schema/

RUN bun install --production

COPY . .

EXPOSE 3000

CMD ["bun", "run", "apps/api/src/index.ts"]
